apiVersion: apps/v1
kind: Deployment
metadata:
  name: runo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runo
  template:
    metadata:
      labels:
        app: runo
    spec:
      containers:
      - name: runo
        image: warriorswitnesses/runo:latest
        ports:
        - containerPort: 9999
        - containerPort: 50051
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: ${DB_USERNAME}
        - name: POSTGRES_PASSWORD
          value: ${DB_PASSWORD}
      imagePullSecrets:
      - name: docker-hub-secret
