apiVersion: v1
kind: Service
metadata:
  name: runo-service
spec:
  selector:
    app: runo
  ports:
    - name: web-port
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: grpc-port
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer
