// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: plagiarism_checker.proto

package plagiarism_checker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckPlagiarismRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageText string `protobuf:"bytes,1,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
}

func (x *CheckPlagiarismRequest) Reset() {
	*x = CheckPlagiarismRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_checker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPlagiarismRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPlagiarismRequest) ProtoMessage() {}

func (x *CheckPlagiarismRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_checker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPlagiarismRequest.ProtoReflect.Descriptor instead.
func (*CheckPlagiarismRequest) Descriptor() ([]byte, []int) {
	return file_plagiarism_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPlagiarismRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

type CheckPlagiarismResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPlagiarized bool    `protobuf:"varint,1,opt,name=is_plagiarized,json=isPlagiarized,proto3" json:"is_plagiarized,omitempty"`
	Similarity    float32 `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
}

func (x *CheckPlagiarismResponse) Reset() {
	*x = CheckPlagiarismResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plagiarism_checker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPlagiarismResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPlagiarismResponse) ProtoMessage() {}

func (x *CheckPlagiarismResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plagiarism_checker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPlagiarismResponse.ProtoReflect.Descriptor instead.
func (*CheckPlagiarismResponse) Descriptor() ([]byte, []int) {
	return file_plagiarism_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPlagiarismResponse) GetIsPlagiarized() bool {
	if x != nil {
		return x.IsPlagiarized
	}
	return false
}

func (x *CheckPlagiarismResponse) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

var File_plagiarism_checker_proto protoreflect.FileDescriptor

var file_plagiarism_checker_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x5f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x67,
	0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x3b,
	0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22, 0x60, 0x0a, 0x17, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x70, 0x6c, 0x61,
	0x67, 0x69, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x69, 0x73, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x32, 0x7f, 0x0a,
	0x11, 0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x72, 0x12, 0x6a, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x67, 0x69,
	0x61, 0x72, 0x69, 0x73, 0x6d, 0x12, 0x2a, 0x2e, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69,
	0x73, 0x6d, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x50, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x5f, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x67,
	0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23,
	0x5a, 0x21, 0x77, 0x68, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x70, 0x79,
	0x2f, 0x70, 0x6c, 0x61, 0x67, 0x69, 0x61, 0x72, 0x69, 0x73, 0x6d, 0x5f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plagiarism_checker_proto_rawDescOnce sync.Once
	file_plagiarism_checker_proto_rawDescData = file_plagiarism_checker_proto_rawDesc
)

func file_plagiarism_checker_proto_rawDescGZIP() []byte {
	file_plagiarism_checker_proto_rawDescOnce.Do(func() {
		file_plagiarism_checker_proto_rawDescData = protoimpl.X.CompressGZIP(file_plagiarism_checker_proto_rawDescData)
	})
	return file_plagiarism_checker_proto_rawDescData
}

var file_plagiarism_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plagiarism_checker_proto_goTypes = []interface{}{
	(*CheckPlagiarismRequest)(nil),  // 0: plagiarism_checker.CheckPlagiarismRequest
	(*CheckPlagiarismResponse)(nil), // 1: plagiarism_checker.CheckPlagiarismResponse
}
var file_plagiarism_checker_proto_depIdxs = []int32{
	0, // 0: plagiarism_checker.PlagiarismChecker.CheckPlagiarism:input_type -> plagiarism_checker.CheckPlagiarismRequest
	1, // 1: plagiarism_checker.PlagiarismChecker.CheckPlagiarism:output_type -> plagiarism_checker.CheckPlagiarismResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plagiarism_checker_proto_init() }
func file_plagiarism_checker_proto_init() {
	if File_plagiarism_checker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plagiarism_checker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPlagiarismRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plagiarism_checker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPlagiarismResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plagiarism_checker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plagiarism_checker_proto_goTypes,
		DependencyIndexes: file_plagiarism_checker_proto_depIdxs,
		MessageInfos:      file_plagiarism_checker_proto_msgTypes,
	}.Build()
	File_plagiarism_checker_proto = out.File
	file_plagiarism_checker_proto_rawDesc = nil
	file_plagiarism_checker_proto_goTypes = nil
	file_plagiarism_checker_proto_depIdxs = nil
}
